// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Contact struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Subject   string
	Message   string
	IpAddress string
	CreatedAt time.Time
}

type Product struct {
	ID              int32
	Url             string
	Source          sql.NullString
	Name            sql.NullString
	Brand           sql.NullString
	Category        sql.NullString
	Price           sql.NullString
	OriginalPrice   sql.NullString
	DiscountPercent sql.NullInt32
	Currency        sql.NullString
	InStock         sql.NullBool
	Rating          sql.NullString
	ReviewCount     sql.NullInt32
	Images          pqtype.NullRawMessage
	Specs           pqtype.NullRawMessage
	CrawledAt       sql.NullTime
	CreatedAt       sql.NullTime
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	UserAgent string
	IpAddress string
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
