// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Contact struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Subject   string
	Message   string
	IpAddress string
	CreatedAt time.Time
}

type Product struct {
	ID              uuid.UUID
	Url             string
	Source          sql.NullString
	Sku             sql.NullString
	Name            sql.NullString
	Brand           sql.NullString
	Category        sql.NullString
	Description     sql.NullString
	Price           sql.NullString
	OriginalPrice   sql.NullString
	DiscountPercent sql.NullInt32
	Currency        sql.NullString
	InStock         sql.NullBool
	Quantity        sql.NullInt32
	Rating          sql.NullString
	ReviewCount     sql.NullInt32
	Images          pqtype.NullRawMessage
	Specs           pqtype.NullRawMessage
	CrawledAt       sql.NullTime
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type ProductsHistory struct {
	HistoryID       uuid.UUID
	ProductID       uuid.UUID
	Url             string
	Source          sql.NullString
	Name            sql.NullString
	Brand           sql.NullString
	Category        sql.NullString
	Price           sql.NullString
	OriginalPrice   sql.NullString
	DiscountPercent sql.NullString
	Currency        sql.NullString
	InStock         sql.NullBool
	Quantity        sql.NullInt32
	Rating          sql.NullString
	ReviewCount     sql.NullInt32
	Images          pqtype.NullRawMessage
	Specs           pqtype.NullRawMessage
	CrawledAt       sql.NullTime
	ChangedAt       time.Time
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	UserAgent string
	IpAddress string
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type WarehouseDimDate struct {
	DateID    int32
	FullDate  time.Time
	Year      int32
	Quarter   int32
	Month     int32
	MonthName string
	Week      int32
	DayOfWeek int32
	DayName   string
	IsWeekend bool
}

type WarehouseDimProduct struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	Url       string
	Name      sql.NullString
	Brand     sql.NullString
	Category  sql.NullString
	Currency  sql.NullString
	Images    pqtype.NullRawMessage
	Specs     pqtype.NullRawMessage
	ValidFrom time.Time
	ValidTo   sql.NullTime
	IsCurrent bool
}

type WarehouseDimSource struct {
	ID        uuid.UUID
	Name      string
	Domain    sql.NullString
	Country   string
	CreatedAt time.Time
}

type WarehouseFactProductSnapshot struct {
	ID              uuid.UUID
	DimProductID    uuid.UUID
	SourceID        uuid.UUID
	DateID          int32
	Price           sql.NullString
	OriginalPrice   sql.NullString
	DiscountPercent sql.NullString
	Quantity        sql.NullInt32
	InStock         sql.NullBool
	Rating          sql.NullString
	ReviewCount     sql.NullInt32
	CrawledAt       time.Time
}
