// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countProductsBySourceAndCategory = `-- name: CountProductsBySourceAndCategory :one
SELECT COUNT(*) FROM products
WHERE ($1::text = '' OR lower(source) = lower($1::text))
AND ($2::text = '' OR lower(category) = lower($2::text))
`

type CountProductsBySourceAndCategoryParams struct {
	Source   string
	Category string
}

func (q *Queries) CountProductsBySourceAndCategory(ctx context.Context, arg CountProductsBySourceAndCategoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProductsBySourceAndCategory, arg.Source, arg.Category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCategoriesBySource = `-- name: GetCategoriesBySource :many
SELECT DISTINCT category FROM products
WHERE ($1::text = '' OR lower(source) = lower($1::text))
AND category IS NOT NULL
ORDER BY category
`

func (q *Queries) GetCategoriesBySource(ctx context.Context, source string) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getCategoriesBySource, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var category sql.NullString
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctSources = `-- name: GetDistinctSources :many
SELECT DISTINCT source FROM products
WHERE source IS NOT NULL
ORDER BY source
`

func (q *Queries) GetDistinctSources(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var source sql.NullString
		if err := rows.Scan(&source); err != nil {
			return nil, err
		}
		items = append(items, source)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, url, source, sku, name, brand, category, subcategory, description, price, original_price, discount_percent, currency, in_stock, quantity, rating, review_count, images, specs, crawled_at, created_at, updated_at FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Source,
		&i.Sku,
		&i.Name,
		&i.Brand,
		&i.Category,
		&i.Subcategory,
		&i.Description,
		&i.Price,
		&i.OriginalPrice,
		&i.DiscountPercent,
		&i.Currency,
		&i.InStock,
		&i.Quantity,
		&i.Rating,
		&i.ReviewCount,
		&i.Images,
		&i.Specs,
		&i.CrawledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductsBySourceAndCategory = `-- name: GetProductsBySourceAndCategory :many
SELECT id, url, source, sku, name, brand, category, subcategory, description, price, original_price, discount_percent, currency, in_stock, quantity, rating, review_count, images, specs, crawled_at, created_at, updated_at FROM products
WHERE ($1::text = '' OR lower(source) = lower($1::text))
AND ($2::text = '' OR lower(category) = lower($2::text))
ORDER BY crawled_at DESC
LIMIT $4 OFFSET $3
`

type GetProductsBySourceAndCategoryParams struct {
	Source     string
	Category   string
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) GetProductsBySourceAndCategory(ctx context.Context, arg GetProductsBySourceAndCategoryParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getProductsBySourceAndCategory,
		arg.Source,
		arg.Category,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Source,
			&i.Sku,
			&i.Name,
			&i.Brand,
			&i.Category,
			&i.Subcategory,
			&i.Description,
			&i.Price,
			&i.OriginalPrice,
			&i.DiscountPercent,
			&i.Currency,
			&i.InStock,
			&i.Quantity,
			&i.Rating,
			&i.ReviewCount,
			&i.Images,
			&i.Specs,
			&i.CrawledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
